name: Check Build Possibility

on:
  pull_request:
    branches:
      - dev
      
jobs:
  try-frontend-build:
    runs-on: ubuntu-20.04
    env: 
      DISABLE_ESLINT_PLUGIN: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.18.0"
      - name: try build frontend
        run: |
          cd ./frontend
          npm install
          npm run build
  try-backend-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "16.18.0"
      - name: change backend directory
        run: cd ./backend
      - name: install backend packages
        run: npm install
      - name: try build backend
        run: npm run build
      - name : backend jest test
        run: npm test
      - name: if fail
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body: "Back-End 테스트 코드를 다시 작성해주세요.",
              event: "REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              pull_number,
              state: "closed"
            })
        if: failure()
